### ISSUE TITLE
Issues with micro and nano

### ISSUE THREAD

**Issue by artemgur** [PerBothner/DomTerm#106] opened 2021-10-30 17:33 UTC
I use the latest Appimage release.

In nano and micro text editors, Enter key doesn't create a new line.

And scrolling with mouse wheel doesn't work correctly in micro. In micro, scrolling with mouse wheel should scroll the document, like in GUI text editors. In domterm, the document does scroll, but also the entire terminal scrolls out of the micro window to the command history.

**Comment by PerBothner** [comment] 2021-10-30 17:36
_"In nano and micro text editors, Enter key doesn't create a new line."_

I was able to reproduce this, using nano and the current git head.  I'll take a look.

**Comment by PerBothner** [comment] 2021-10-30 18:11
The problem is what to send when Enter is pressed: CR, NL, or NR+NL. Nano and Micro are a bit picker than most ediors, and require CR, not NL. DomTerm should send CR, not NL, but there are some complications. As a short-term work-around you can type ^M (control-M) instead of Enter, but I'll try to fix this and make a new AppImage ASAP.

**Comment by PerBothner** [comment] 2021-10-30 21:14
I checked in a fix.  I also created a new 2.9.4 AppImage release including the fix and a number of updates. Please try it out.

**Comment by artemgur** [comment] 2021-11-01 21:22
Now enter works fine both in nano and micro, thanks!

**Closed** 2021-11-01 22:27 UTC
